import { LandingPage } from "@/types";
import { Button } from "@/components/ui/button";
import { Check, ChevronDown, ArrowLeft } from "lucide-react";

interface LandingPageViewProps {
    data: LandingPage;
    onBack: () => void;
}

export function LandingPageView({ data, onBack }: LandingPageViewProps) {
    return (
        <div className="w-full max-w-4xl mx-auto bg-white text-black rounded-xl overflow-hidden shadow-2xl animate-in zoom-in-95 duration-500">

            {/* Navigation / Header (Mock Browser) */}
            <div className="bg-gray-100 border-b p-3 flex items-center justify-between">
                <div className="flex gap-2">
                    <div className="w-3 h-3 rounded-full bg-red-400" />
                    <div className="w-3 h-3 rounded-full bg-yellow-400" />
                    <div className="w-3 h-3 rounded-full bg-green-400" />
                </div>
                <div className="text-xs text-gray-400 font-mono">landing-page-preview.html</div>
                <Button variant="ghost" size="sm" onClick={onBack} className="h-6 text-xs hover:bg-gray-200 text-gray-600">
                    <ArrowLeft className="mr-1 h-3 w-3" /> Back to Offers
                </Button>
            </div>

            {/* Hero Section */}
            <div className="px-8 py-16 md:py-24 text-center space-y-6 max-w-2xl mx-auto">
                <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-gray-900 leading-tight">
                    {data.headline}
                </h1>
                <p className="text-xl text-gray-600 leading-relaxed">
                    {data.subheadline}
                </p>
                <div className="pt-4">
                    <Button size="lg" className="bg-black hover:bg-gray-800 text-white text-lg px-8 py-6 rounded-full shadow-lg hover:shadow-xl transition-all">
                        {data.call_to_action}
                    </Button>
                </div>
            </div>

            {/* Value Stack */}
            <div className="bg-gray-50 px-8 py-12">
                <div className="max-w-2xl mx-auto space-y-4">
                    <h3 className="text-sm font-bold uppercase tracking-wider text-gray-400 text-center mb-8">What's Included</h3>
                    <div className="grid gap-4">
                        {data.value_bullets.map((bullet, i) => (
                            <div key={i} className="flex items-start gap-4 p-4 bg-white rounded-lg border border-gray-100 shadow-sm">
                                <div className="bg-green-100 text-green-700 p-1 rounded-full shrink-0 mt-0.5">
                                    <Check className="h-4 w-4" />
                                </div>
                                <span className="font-medium text-gray-800">{bullet}</span>
                            </div>
                        ))}
                    </div>
                </div>
            </div>

            {/* FAQ Section */}
            <div className="px-8 py-16 max-w-2xl mx-auto space-y-8">
                <h3 className="text-2xl font-bold text-center text-gray-900">Frequently Asked Questions</h3>
                <div className="space-y-4">
                    {data.faqs.map((faq, i) => (
                        <div key={i} className="border-b border-gray-200 pb-4">
                            <h4 className="font-semibold text-gray-900 mb-2 flex items-center justify-between">
                                {faq.question}
                                <ChevronDown className="h-4 w-4 text-gray-400" />
                            </h4>
                            <p className="text-gray-600 text-sm leading-relaxed">
                                {faq.answer}
                            </p>
                        </div>
                    ))}
                </div>
            </div>

            <div className="bg-gray-900 text-white py-8 text-center text-sm text-gray-400">
                <p>Generated by AI Offer Generator</p>
            </div>

        </div>
    );
}
